<?php

include_once 'database/DatabaseRecord.php';
include_once 'database/DatabaseTable.php';

class DatabaseWorker {
    private $connection = null;
    
    public function __construct($connection) {
        $this->connection = $connection;
    }
    
    public function insert($record) {
        try {
            $table = $record->getTable();
            foreach ($table->getFields() as $fieldName) {
                if (strcmp($fieldName, 'id')) {
                    if (strlen($fields) > 0)
                        $fields .= ', ';
                    $fields .= $fieldName;

                    if (strlen($values) > 0)
                        $values .= ', ';
                    
                    $fieldValue = $record->__get($fieldName);
                    if (!isset($fieldValue))
                        throw new Exception('*** DatabaseWorker: ' . $fieldName . ' field is empty');
                    
                    if (is_string($fieldValue))
                        $fieldValue = '\'' . mysql_escape_string($fieldValue) . '\'';
                    $values .= $fieldValue;
                }
            }

            $query = 'insert into ' . $record->getTable()->getName() . '(' . $fields . ') values (' . $values . ')';
            $this->execQuery($query);
            
            $record->id = $this->connection->getAutogeneratedInsertId();
        } catch (Exception $e) {
            echo $e->getMessage();
        }
    }
    
    public function delete($record) {
        try {
            $query = 'delete from ' . $record->getTable()->getName() . ' where id=' . $record->getId();
            $this->execQuery($query);
        } catch (Exception $e) {
            echo $e->getMessage();
        }
    }
    
    public function update($record) {
        try {
            foreach ($record->getTable()->getFields() as $fieldName) {
                if ($record->isFieldModified($fieldName)) {
                    if (strlen($fields) > 0)
                        $fields .= ' and ';
                    $fields .= $fieldName . '=';
                    
                    $fieldValue = $record->__get($fieldName);
                    if (!isset($fieldValue))
                        throw new Exception('*** DatabaseWorker: ' . $fieldName . ' field is empty');
                    
                    if (is_string($fieldValue))
                        $fieldValue = '\'' . mysql_escape_string($fieldValue) . '\'';
                    
                    $fields .= $fieldValue;
                }
            }
        
            $query = 'update ' . $record->getTable()->getName() . ' set ' . $fields . ' where id = ' . $record->getId();
            $this->execQuery($query);
        } catch (Exception $e) {
            echo $e->getMessage();
        }
    }
    
    private function execQuery($query) {
        if (isset($this->connection)) {
            echo $query . '<br>';
            $this->connection->exec($query);
        } else {
            throw new Exception('*** DatabaseWorker: Invalid connection');
        }
    }
}

?>