<?php

include_once "database/DatabaseStatement.php";

class DatabaseConnection {
    private $handle = null;
    private $host = null;
    private $database = null;
    private $username = null;
    private $password = null;
    private $isConnected = false;
    
    /* Shared connection. This class can be as singleton. 
    I think it need to rewrite. */
    private static $__sharedConnection__ = null;
    public static function sharedConnection($host='', $database='', $username='', $password='') {
        if (!self::$__sharedConnection__) {
            self::$__sharedConnection__ = new DatabaseConnection($host, $database, $username, $password);
            self::$__sharedConnection__->openNewConnection();
        }

        return self::$__sharedConnection__;
    }
    
    public function __construct($host, $database, $username, $password) {
        $this->database = $database;
        $this->host = $host;
        $this->username = $username;
        $this->password = $password;
    }
    
    public function __destruct() {
        $this->close();
    }
    
    public function openNewConnection() {
        try {
            $this->handle = mysql_connect($this->host, $this->username, $this->password, true);
            mysql_select_db($this->database);
            
            if (!$this->handle)
                throw new Exception('MySQL Connection Database error: ' . mysql_error());
            
            $this->isConnected = true;
        } catch (Exception $e) {
            echo $e->getMessage();
        }
    }
    
    public function open() {
        if (!$this-isConnected()) {
            try {
                $this->handle = mysql_connect($this->host, $this->username, $this->password);
                mysql_select_db($this->database);

                if (!$this->handle)
                    throw new Exception('MySQL Connection Database error: ' . mysql_error());

                $this->isConnected = true;
            } catch (Exception $e) {
                echo $e->getMessage();
            }
        } else {
            echo 'Error: Connection already opened';
        }
    }
    
    public function close() {
        if ($this->isConnected()) {
            mysql_close($this->handle);
            $this->isConnected = false;
        } else {
            echo 'Error: Connection already closed';
        }
    }
    
    public function exec($query) {
        if ($this->isConnected()) {
            return mysql_query($query);
        }
        return false;
    }
    
    public function getAutogeneratedInsertId() {
        return mysql_insert_id();
    }
    
    public function isConnected() {
        return $this->isConnected;
    }
    
    public function statement($query) {
        return new DatabaseStatement($this, $query);
    }
}

?>